---

name: ChangelogChecker
"on":
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - develop
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog checker
        uses: Zomzog/changelog-checker@564f4aa7a062e7498bd253f616569f02fb024c06
        with:
          fileName: CHANGELOG.md
          #noChangelogLabel: my custom label # default `no changelog`
          checkNotification: Simple # default `Detailed`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

